### ISSUE TITLE
Plugin able to track runes / cdr boots?

### ISSUE THREAD

**Issue by varw3n** [mysnphit/ElgatoLeagueTracker#1]
Hey, thank you for this Plugin. I got a question regarding the Cooldoown behind each summoner. Is the Plugin able to recognize players runes and if they exist, their cooldown redution boots, and adapt the timer behind each summoner? For example: Teleport CD gets reduced to 06:15 because of boots mid-game?

**Comment by mysnphit** [comment]
Hello,

The plugin takes into account items and levels. Runes are still to be added, since these are not easily accessible via the livegamedata api that Riot provides.

For example, here you can see how the base cds are calculated (only tp is based on lvl):
```
var cooldowns = {
	"Cleanse": function(player) { return 210 } ,
	"Exhaust": function(player) { return 210 },
	"Flash": function(player) { return 300 },
	"Ghost": function(player) { return 210 },
	"Heal": function(player) { return 240 },
	"Smite": function(player) { return 15 },
	"Teleport": function(player) { return 420 - (10 * player.level) },
	"Clarity": function(player) { return 240 },
	"Ignite": function(player) { return 180 },
	"Barrier": function(player) { return 180 },
	"Mark": function(player) { return 80 }
}
```
We take the base cds and use them in this formula, which also takes into account lucidity boots (item id 3173).
```
// We cant detect the rune that gives 0.05 reduction, so we just add it to the error margin
var timing = parseInt(cooldowns[spells[key]](player) * (1 - 0.06 - Math.min(1, player.items.filter(x => x.itemID == 3173).length) * 0.10))						
```

Hope this helps!
